#!/usr/bin/env bash
# Function to display information about a subdomain

display_subdomain_info() {
    local domain="$1"
    local subdomain="$2"

    # Get the DNS record for the subdomain
    
    dig_output=$(dig "$subdomain.$domain")
    answer_section_line=$(echo "$dig_output" | awk '/^;; ANSWER SECTION:/{print NR}')
    dns_record_type=$(echo "$dig_output" | awk -v line="$answer_section_line" 'NR == line+1 {print $4}')
    ip_address=$(echo "$dig_output" | awk -v line="$answer_section_line" 'NR == line+1 {print $5}')

    # Get the record type (A or CNAME)
    # destination=$(echo "$ip_address" | awk 'NR==1 {print $1}')

    # Get the destination IP or hostname
    # record_type=$(echo "$dns_record" | awk 'NR==1 {print $2}')

    # Display the information
    echo "The subdomain $subdomain is a $dns_record_type record and points to $ip_address"
}

# Main script
if [ "$#" -lt 1 ]; then
    echo "Error: Missing domain parameter."
    echo "Usage: $0 domain [subdomain]"
    exit 1
fi

domain="$1"
subdomain="$2"

if [ -z "$subdomain" ]; then
    # Display information for default subdomains www, lb-01, web-01, and web-02
    display_subdomain_info "$domain" "www"
    display_subdomain_info "$domain" "lb-01"
    display_subdomain_info "$domain" "web-01"
    display_subdomain_info "$domain" "web-02"
else
    # Display information for the specified subdomain
    display_subdomain_info "$domain" "$subdomain"
fi

