#!/usr/bin/env bash
#Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)
# Update package lists
sudo apt update

# Install Nginx
sudo apt install -y nginx

# Verify if Nginx is installed successfully
if [ $(dpkg-query -W -f='${Status}' nginx 2>/dev/null | grep -c "ok installed") -eq 0 ]; then
    echo "Nginx installation failed. Exiting."
    exit 1
fi

# Create a simple HTML file with "Hello World!" message
echo "<hi>Hello World!</hi>" | sudo tee /var/www/html/index.html > /dev/null

# Create a custom Nginx configuration file for the custom HTTP response header
cat <<EOL | sudo tee /etc/nginx/conf.d/custom_header.conf > /dev/null
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html;
    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }

    # Add custom HTTP response header
    add_header X-Served-By \$hostname;
}
EOL

# Remove default Nginx configuration files
sudo rm /etc/nginx/sites-enabled/default

# Restart Nginx to apply the changes
sudo systemctl restart nginx

echo "Nginx has been installed and configured with custom HTTP response header successfully."
